baseURL: "https://fboehm.us/"
languageCode: "en-us"
title: "Frederick Boehm's website"
enableEmoji: true
googleAnalytics: UA-46757486-5
pygmentsCodefences: true
pygmentsStyle: "lovelace"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
canonifyURLs: true
permalinks:
  blog: "/blog/:slug/"

author:
  name: "Frederick Boehm"
  email: "frederick.boehm@gmail.com"
params:
  title: ""
  copyright: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
  description: ""
rssLimit: 50
