baseurl: "https://www.noamross.net/"
languageCode: "en-us"
title: "noamross.net"
enableEmoji: true
enableRobotsTXT: true
pygmentsCodefences: true
pygmentsStyle: "lovelace"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

permalinks:
  musings: "/:year/:month/:slug/"
  archives: "/archives/:filename/"

author:
  name: "Noam Ross"
  email: "noam.ross@gmail.com"
copyright: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
description: "noamross.net"
rssLimit: 50

