theme: "noamross"
baseURL: "https://fboehm.us/"
languageCode: "en-us"
title: "fboehm.us"
enableRobotsTXT: true
enableEmoji: true
enableGitInfo: true
googleAnalytics: UA-46757486-5
pygmentsCodefences: true
pygmentsStyle: "lovelace"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "public/notebook/.git", "static/notebook/.git"]
canonifyURLs: false
permalinks:
  blog: "/blog/:slug/"
author:
  name: "Frederick J. Boehm"
  email: "frederick.boehm@gmail.com"
params:
  title: "fboehm.us"
  copyright: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
  description: "Frederick Boehm's website"
rssLimit: 50
