---
title: "Research"
toc: true
---

## Overview

I study statistical methods and apply them to biomedical research questions. 



---

## Human Genetics and Statistics

I first started working with genome-wide association studies in 2007 as a member of the genetic data quality control team for the Genes and Environment consortium at the University of Washington. More recently, I've focused on statistical methods for analyzing large-scale human genetics data. 

Our current work includes the development of methods for analyzing biobank-scale data. One project addresses construction of polygenic risk scores. Polygenic risk scores summarize an individual's genetic risk for a disease. They are becoming more important in clinical and public health settings, where they can be used to identify subjects at high risk of disease.






### Selected Publications

1.  Christina G. Hutten, Frederick J. Boehm, Jennifer A. Smith, Brian W. Spitzer, Sylvia Wassertheil-Smoller, Carmen R. Isasi, Jianwen
Cai, Jonathan T. Unkart, Jiehuan Sun, Victoria Persky, Martha L. Daviglus, Tamar Sofer, and Maria Argos (2025). Differential
performance of polygenic risk scores for heart disease in hispanic/latino subgroups: Findings of the hispanic community health
study/study of latinos. Human Genetics and Genomics Advances 6(4):100486. https://doi.org/10.1016/j.xhgg.2025.100486.

2. Frederick J. Boehm and Xiang Zhou (2022). Statistical methods for mendelian randomization in genome-wide association studies:
A review. Computational and Structural Biotechnology Journal 20:2338-2351. https://doi.org/10.1016/j.csbj.2022.05.015.


3. Cathy C. Laurie, Kimberly F. Doheny, Daniel B. Mirel, Elizabeth W. Pugh, Laura J. Bierut, Tushar Bhangale, Frederick Boehm,
Neil E. Caporaso, Marilyn C. Cornelis, Howard J. Edenberg, Stacy B. Gabriel, Emily L. Harris, Frank B. Hu, Kevin B. Jacobs, Peter
Kraft, Maria Teresa Landi, Thomas Lumley, Teri A. Manolio, Caitlin McHugh, Ian Painter, Justin Paschall, John P. Rice, Kenneth M.
Rice, Xiuwen Zheng, Bruce S. Weir, and for the GENEVA Investigators (2010). Quality control and quality assurance in genotypic
data for genome‐wide association studies. Genetic Epidemiology 34(6):591-602. https://doi.org/10.1002/gepi.20516.



---

## Observational Studies and Causal Inference

We also work on statistical methods to characterize causal effects in observational studies. One application of this work is in the study of environmental pollutants on preterm births.


---

## Statistics and Mathematics Education Research

I'm interested in developing and evaluating methods for teaching statistics and mathematics. Some of this work involves curriculum development, while other projects address best practices for group data analysis projects in the classroom. 




### Selected Publications

1. Frederick J. Boehm and Bret M. Hanlon (2021). What is happening on twitter? A framework for student research projects with tweets. Journal of Statistics and Data Science Education 29:S95-S102. https://doi.org/10.1080/10691898.2020.1848486.


---

## Mouse Genetics and Statistics

In my Ph.D. and postdoctoral research, I worked on statistical methods for mouse genetics data. Our goals included the development of a deeper understanding of the genetic architecture of complex traits. One project involved developing a statistical method for discerning between pleiotropy and multiple linked loci in multiparental mouse populations, like the Diversity Outbred. We then collaborated with biologists to apply this method to gut microbiome-derived traits. In this context, we developed the `qtl2pleio` R package, which is available on Github.



### Selected Publications

1. Sherry L. Kurtz, Richard E. Baker, Frederick J. Boehm, Chelsea C. Lehman, Lara R. Mittereder, Hamda Khan, Amy P. Rossi, Daniel
M. Gatti, Gillian Beamer, Christopher M. Sassetti, and Karen L. Elkins (2024-03-07). Multiple genetic loci influence vaccine-induced
protection against mycobacterium tuberculosis in genetically diverse mice. PLOS Pathogens 20(3):e1012069. https://doi.org/10.1371/
journal.ppat.1012069.

2. Clare M Smith, Richard E Baker, Megan K Proulx, Bibhuti B Mishra, Jarukit E Long, Sae Woong Park, Ha-Na Lee, Michael C
Kiritsy, Michelle M Bellerose, Andrew J Olive, Kenan C Murphy, Kadamba Papavinasasundaram, Frederick J Boehm, Charlotte
J Reames, Rachel K Meade, Brea K Hampton, Colton L Linnertz, Ginger D Shaw, Pablo Hock, Timothy A Bell, Sabine Ehrt,
Dirk Schnappinger, Fernando Pardo-Manuel De Villena, Martin T Ferris, Thomas R Ioerger, and Christopher M Sassetti (2022-
02-03). Host-pathogen genetic interactions underlie tuberculosis susceptibility in genetically diverse mice. eLife 11:e74419. https:
//doi.org/10.7554/eLife.74419.

3. Julia H. Kemis, Vanessa Linke, Kelsey L. Barrett, Frederick J. Boehm, Lindsay L. Traeger, Mark P. Keller, Mary E. Rabaglia, Kathryn
L. Schueler, Donald S. Stapleton, Daniel M. Gatti, Gary A. Churchill, Daniel Amador-Noguez, Jason D. Russell, Brian S. Yandell, Karl
W. Broman, Joshua J. Coon, Alan D. Attie, and Federico E. Rey (2019). Genetic determinants of gut microbiota composition
and bile acid profiles in mice. PLOS Genetics 15(8):e1008073. https://doi.org/10.1371/journal.pgen.1008073.

4. Frederick J. Boehm, Elissa J. Chesler, Brian S. Yandell, and Karl W. Broman (2019). Testing Pleiotropy vs. Separate QTL in Multiparental Populations. G3 9(7): 2317-2324. https://doi.org/10.1534/g3.119.400098


---

## Other Collaborations

I've also collaborated with researchers in many different fields, including biology, medicine, mass communications, literature, genetics, and others. I enjoy learning new fields and communicating statistical ideas to non-statisticians.


### Selected Publications

1. Chris Wells, Dhavan V. Shah, Jon C. Pevehouse, JungHwan Yang, Ayellet Pelled, Frederick Boehm, Josephine Lukito, Shreenita
Ghosh, and Jessica L. Schmidt (2016). How trump drove coverage to the nomination: Hybrid media campaigning. Political
Communication 33(4):669-676. https://doi.org/10.1080/10584609.2016.1224416.

2. Eric C. Tauchman, Frederick J. Boehm, and Jennifer G. DeLuca (2015). Stable kinetochore–microtubule attachment is
sufficient to silence the spindle assembly checkpoint in human cells. Nature Communications 6(1):10036. https://doi.org/10.1038/
ncomms10036.