version: 2
jobs:
  build:
    working_directory: ~/main
    docker:
      - image: rocker/verse:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps1-$R_VERSION-{{ .Branch }}-{{ checksum "DESCRIPTION" }}-{{ checksum ".circleci/config.yml" }}
            - deps1-$R_VERSION-{{ .Branch }}
            - deps1-$R_VERSION
      - run:
          command: |
            if [ -f DESCRIPTION ]; then R --quiet -e "devtools::install(dep = TRUE)"; fi
            Rscript -e "blogdown::install_hugo()"
      - save_cache:
          key: deps1-$R_VERSION-{{ .Branch }}-{{ checksum "DESCRIPTION" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - "/usr/local/lib/R/site-library"
      - run:
          command: |
            Rscript -e "blogdown::build_site()"
      - store_artifacts:
          path: /root/main/artifacts/
          destination: artifacts
      - add_ssh_keys:
          fingerprints:
            - "7c:cf:69:c8:f8:86:24:81:66:70:a6:18:72:1f:ca:07"
      - deploy:
          name: "Rsync to site"
          command: |
            rsync -avz --delete public/ noamross_noamross@ssh.phx.nearlyfreespeech.net:/home/public/test-site
